# Generated by Django 5.2 on 2025-05-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(auto_now_add=True)),
                ('survey_time', models.TimeField(auto_now_add=True)),
                ('project', models.CharField(choices=[('Western_Australia', 'Western Australia'), ('Northern_Territory', 'Northern Territory'), ('Queensland', 'Queensland'), ('Southern_Australia', 'Southern Australia'), ('New_South_Wales', 'New South Wales'), ('Tasmania', 'Tasmania')], default='Western_Australia')),
                ('area', models.TextField()),
            ],
        ),
    ]
