# Generated by Django 5.2 on 2025-05-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('australia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='project',
            new_name='territory',
        ),
    ]
