# Generated by Django 5.2 on 2025-05-11 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('australia', '0002_rename_project_questionnaire_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='survey_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='survey_time',
            field=models.TimeField(default=datetime.datetime(2025, 5, 11, 18, 5, 58, 265336, tzinfo=datetime.timezone.utc)),
        ),
    ]
