# Generated by Django 5.2 on 2025-05-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('australia', '0004_alter_questionnaire_survey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='survey_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='survey_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
