# Generated by Django 5.2 on 2025-05-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('australia', '0007_alter_questionnaire_survey_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchers', models.CharField(choices=[('Bwana_Waziri', 'Bwana Waziri'), ('Samuel_Gachuhi', 'Samuel Gachuhi'), ('Jane_Otieno', 'Jane Otieno'), ('Janet_Awino', 'Janet Awino'), ('William_Kinyanjui', 'William Kinyanjui'), ('Johnson_Ngugi', 'Johnson Ngugi')], default='Bwana_Waziri')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='recorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='australia.researcher'),
            preserve_default=False,
        ),
    ]
