# Generated by Django 5.2 on 2025-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('australia', '0008_researcher_questionnaire_recorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='images',
            field=models.FileField(blank=True, upload_to='image-%Y-%m-%d'),
        ),
    ]
